package:
  name: python-libsbml
  version: "5.18.0"

source:
  url: https://files.pythonhosted.org/packages/14/21/70fa01b5df02ab4969718e8508feb5bc1ff5d63d73db684d1877ae764f24/python-libsbml-5.18.0.tar.gz
  sha256: 58e36e83c3763887f56a6e51fe9ba3bb5ad903d7bc1be028b57bc147c1ab5ea1
  patches:
    - fix_path.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - libxml2
    - bzip2
    - libxml2
  run:
    - python
    - bzip2
    - libxml2

test:
  imports:
    - libsbml

about:
  home: http://sbml.org
  license: LGPL
  summary: 'LibSBML Python API. LibSBML is a library for reading, writing and manipulating the Systems Biology Markup Language (SBML).'

extra:
  skip-lints:
    - already_in_bioconda
