package:
  name: hichipper
  version: "0.7.7"

source:
  url: https://files.pythonhosted.org/packages/cd/15/be102dad402d3c03ac069e625bc0918d8eeaa5571d28580804665d949712/hichipper-0.7.7.tar.gz
  sha256: 279a6f40f5ac5188004710e9dd63fe654e682684797fda39ca6fc2d93c6614ea

build:
  entry_points:
    - hichipper = hichipper.cli:main
  number: 0
  skip: True  # [py3k]

requirements:
  host:
    - python
    - setuptools
    - click
    - pyyaml
    - numpy
    - macs2
  run:
    - python
    - click
    - pyyaml
    - numpy
    - macs2

test:
  imports:
    - hichipper

  commands:
    - hichipper --help

about:
  home: https://github.com/aryeelab/hichipper
  license: BSD License
  summary: Processing HiChIP data into loops.
  license_family: BSD

