package:
  name: perl-apache-test
  version: "1.41"

build:
  number: 0

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHAY/Apache-Test-1.41.tar.gz
  sha256: 38cf60b9d63156a8043b8fc75b1b41132fa35228910e61089e08bb84869ab018

requirements:
  host:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker

  run:
    - perl
    - perl-pathtools

test:
  imports:
    - Apache::Test

about:
  home: http://metacpan.org/pod/Apache::Test
  license: unknown
  summary: 'Special Tests Sequence Failure Finder'
