{% set version = "1.4.0" %}
{% set name = "hivclustering" %}

package:
  name: python-{{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/veg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 52ac2022dc57ab71a7e7ccc4a9467814957db4189d228257dd0185b7f82c5acb
  patches:
    #- setup.patch

build:
  number: 0
  skip: True # [py27]

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - python-bioext >=0.18.0
    - python-hyphy-python >=0.1.6
    - python-hppy >=0.9.6

test:
  imports:
    - hivclustering

about:
  home: https://github.com/veg/hivclustering
  license: MIT
  summary: 'A Python 3 library that makes inferences on HIV-1 transmission networks.'
