{% set name = "bbknn" %}
{% set version = "1.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2663435526010a3969af1086a40782a9ebcc963cd0fe4a091ae5b5cc42425b53

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python-annoy
    - cython
    - numpy >=1.13
    - pip
    - python
    - scipy
    - scikit-learn
    - umap-learn
  run:
    - python-annoy
    - cython
    - numpy >=1.13
    - python
    - scipy
    - scikit-learn
    - umap-learn

test:
  imports:
    - bbknn

about:
  home: https://github.com/Teichlab/bbknn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Batch balanced KNN

extra:
  recipe-maintainers:
    - jenzopr
