package:
  name: perl-sanger-cgp-vagrent
  version: '3.3.4'

source:
  url: https://github.com/cancerit/VAGrENT/archive/v3.3.4.tar.gz
  sha256: 39c9c8caaa247c703eaf65fb55c28a4c135414ed242e5de77a8ab1278f3dd06f

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-module-build
    - perl-file-sharedir-install
    - perl-bio-db-hts
    - perl-sub-exporter-progressive
  run:
    - perl
    - perl-bio-db-hts
    - perl-sub-exporter-progressive

test:
  imports:
    - Sanger::CGP::Vagrent

about:
  home: https://github.com/cancerit/VAGrENT
  license: GPLv3
  summary: A toolset for comparing genomic variants to reference genome annotation to identify potential biological consequences
