{% set name = "perl-module-corelist" %}
{% set version = "5.20190620" %}
{% set sha256 = "319092da2ca6432549dd054da43a349ec6afd29a1ac3e8be779c130d283b2159" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-CoreList-5.20190620.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-version
    - perl-extutils-makemaker

  run:
    - perl
    - perl-version

test:
  imports:
    - Module::CoreList
    - Module::CoreList::Utils

about:
  home: http://dev.perl.org/
  license: perl_5
  summary: 'what modules shipped with versions of perl'
