{% set version = "1.0.20190228134645" %}
package:
  name: cwltest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltest/cwltest-{{ version }}.tar.gz
  sha256: 317a917d0ed18e5db9dab1069f32222625e350b35d53f36b5b7430538006eadb


build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - schema-salad >=1.14
    - typing >=3.5.3,<3.6
    - junit-xml >=1.8
    - futures >=3.0.5 # [py27]
    - subprocess32 >=3.5.0 # [py27]
    - cachecontrol <0.12,>=0.11.7
    - mistune <0.8,>=0.7.3

  run:
    - python
    - schema-salad >=1.14
    - typing >=3.5.3,<3.6
    - junit-xml >=1.8
    - futures >=3.0.5 # [py27]
    - subprocess32 >=3.5.0 # [py27]
    - cachecontrol <0.12,>=0.11.7
    - mistune <0.8,>=0.7.3

test:
  imports:
    - cwltest
  commands:
    - cwltest --help

about:
  home: https://github.com/common-workflow-language/cwltest
  license: Apache License 2.0
  summary: Framework for testing CWL tools and workflows
