{% set version = '0.1.1' %}

package:
  name: r-kaos
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kaos_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kaos/kaos_{{ version }}.tar.gz
  sha256: 98090a008de946374627c70748ea0b1b78ec7b803b9361fc837c32f254ffd721

build:
  merge_build_host: True
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggplot2
    - r-reshape2

  run:
    - r-base
    - r-ggplot2
    - r-reshape2

test:
  commands:
    - $R -e "library('kaos')"

about:
  home: https://CRAN.R-project.org/package=kaos
  license: GPL (>= 2)
  summary: "Sequences encoding by using the chaos game representation. L\xF6chel et al. (2019)
    <doi:10.1101/575324>."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
