{% set version = "0.1.9" %}
{% set github = "https://github.com/acidgenomics/freerange" %}

package:
  name: r-freerange
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 36a369e67a56f0ce79ab8ce19fc9cc0e3082cc8805bf7d69595432b4ebf1d022

build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base
    - r-brio >=0.2.0
    - r-goalie >=0.2.16
    - r-syntactic >=0.1.9
    - r-transformer >=0.1.11
    - bioconductor-annotationhub
    - bioconductor-biocgenerics
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-dplyr >=0.8
    - r-magrittr >=1.5
    - r-rlang >=0.3
    - r-tibble >=2.1

  run:
    - r-base
    - r-brio >=0.2.0
    - r-goalie >=0.2.16
    - r-syntactic >=0.1.9
    - r-transformer >=0.1.11
    - bioconductor-annotationhub
    - bioconductor-biocgenerics
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-dplyr >=0.8
    - r-magrittr >=1.5
    - r-rlang >=0.3
    - r-tibble >=2.1

test:
  commands:
    - $R -e "library('freerange')"

about:
  home: https://freerange.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: Generate and manipulate genomic ranges.
