{% set version = "3.7.2" %}

package:
  name: weblogo
  version: {{ version }}

build:
  noarch: python
  number: 0

source:
  url: https://github.com/WebLogo/weblogo/archive/3.7.2.tar.gz
  sha256: 23a11a14ac91e4618eab1bf51658b602a554faf8cb34670b3bad2f21d92b077a

requirements:
  host:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - ghostscript

test:
  imports:
    - corebio
    - corebio.seq_io
    - corebio.seq_io._nexus
    - corebio.utils
    - weblogolib
  commands:
    - weblogo -h
    - transformseq -h

about:
  home: https://github.com/WebLogo/weblogo
  license: MIT
  summary: 'WebLogo3 : Sequence Logos Redrawn'
  license_family: MIT

extra:
  identifiers:
    - biotools:weblogo
    - doi:10.1101/gr.849004
