{% set version = "0.2.18" %}
{% set github = "https://github.com/acidgenomics/goalie" %}

package:
  name: r-goalie
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 0590482d8c800b2c8fca2a39ce4651bbf467cce9a5b83bbec58ade3b350e2ab4
  
build:
  number: 0

requirements:
  host:
    - r-base
    - r-backports
    - r-curl >=3.2

  run:
    - r-base
    - r-backports
    - r-curl >=3.2

test:
  commands:
    - $R -e "library('goalie')"

about:
  home: https://goalie.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  summary: Assertive check functions for defensive R programming.

extra:
  recipe-maintainers:
    - mjsteinbaugh
    - pinin4fjords
    - chapmanb
