{% set version="1.9.2" %}

package:
  name: synapseclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/synapseclient/synapseclient-{{ version }}.tar.gz
  sha256: 981b7b681728e9c23729a130677fa0bb9b6a06e189bc3171c565af163fbcf874

build:
  noarch: python
  skip: False
  entry_points:
    - synapse = synapseclient.__main__:main
  number: 0

requirements:
  host:
    - python
    - setuptools
    - requests >=1.2
    - six
    - future
    - backports.csv
    - deprecated >=1.2.3
    - keyring >=12.0.2

  run:
    - python
    - requests >=1.2
    - six
    - future
    - backports.csv
    - deprecated >=1.2.3
    - keyring >=12.0.2
  run_constrained:
    - pandas >=0.23.0
    - pysftp >=0.28

test:
  imports:
    - synapseclient
  commands:
    - synapse --help
  
about:
  home: http://synapse.sagebase.org/
  dev_url: https://github.com/Sage-Bionetworks/synapsePythonClient
  license: Apache Software License
  summary: Python client for Synapse
  description: |
    A client for Synapse, a collaborative compute space  that allows
    scientists to share and analyze data together.
