{% set name = "perl-gtdbtk" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/Ecogenomics/GTDBTk/archive/{{ version }}.tar.gz
  sha256: eec80962182f7f14fbc3c802c1db36e48c1fd356c269692b4206c69ab5c6325a

build:
  number: 0

  noarch: generic
requirements:
  host:
    - perl
    - perl-moose
    - perl-ipc-run
    - perl-bioperl
  run:
    - perl
    - perl-moose
    - perl-ipc-run
    - perl-bioperl >=1.7.2

test:
  commands:
    - pfam_search.pl -h

about:
  home: https://github.com/Ecogenomics/GTDBTk
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Perl script and dependent library files required for GTDB-Tk.'
