package:
  name: simka
  version: 1.5.0  

build:
  number: 0

source:
  url: https://github.com/GATB/simka/releases/download/v1.5.0/simka-v1.5.0-Source.tar.gz
  sha256: 30d77a9018eefaab46defaf23fc032278fe24046bd3f12e2d6378ce51eb676d6

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - simka -h

about:
  home: https://github.com/GATB/simka
  license: file
  license_file: LICENSE
  summary: Simka is a de novo comparative metagenomics tool. Simka represents each dataset as a k-mer spectrum and compute several classical ecological distances between them.
extra:
  identifiers:
    - biotools:Simka
    - doi:10.7717/peerj-cs.94
