{% set name = "pydna" %}
{% set version = "3.0.1" %}
{% set hash = "79bcb2f5f02bfa95f8ddf091581a352634dc985510eebe58cb7ef9a7b13a546d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py27]

source:
  url: https://github.com/BjornFJohansson/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
    - setup.patch

requirements:
  host:
  - python
  - setuptools
  - biopython >=1.65
  - networkx >=1.8.1
  - appdirs >=1.3.0
  - prettytable >=0.7.2
  - ordered-set >=2.0.1
  - pyparsing >=2.1.10
  - requests >=2.12
  - pytest-runner

  run:
  - python
  - biopython >=1.65
  - networkx >=1.8.1
  - appdirs >=1.3.0
  - prettytable >=0.7.2
  - ordered-set >=2.0.1
  - pyparsing >=2.1.10
  - requests >=2.12
  - pytest-runner

test:
  imports:
    - pydna

about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Representing double stranded DNA and simulating cloning, homologous recombination, Gibson assembly, Gel electrophoresis etc.'
