{% set SLICEDIMAGE_VERSION = "3.2.0" %}

package:
  name: slicedimage
  version: {{ SLICEDIMAGE_VERSION }}

source:
  url:  https://github.com/spacetx/slicedimage/archive/{{ SLICEDIMAGE_VERSION }}.zip
  sha256: 7d05e8508ce2dcdcf5e738ac78ffe25c9a36d7e135f08eff2de5e162e9d83895

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy !=1.13.0
    - diskcache
    - packaging
    - requests
    - scikit-image
    - six

test:
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  summary: Python module to access sliced imaging data
