package:
  name: perl-lwp-simple
  version: '6.39'

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.39.tar.gz
  sha256: 9a8d7747938aa75d7d524c71574ae7f99ca66a5dac8255a7f7759f373e7774d5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-encode-locale
    - perl-module-build
    - perl-net-http
    - perl-html-parser
    - perl-uri
    - perl-http-cookies
    - perl-http-date
    - perl-libwww-perl

  run:
    - perl
    - perl-encode-locale
    - perl-net-http
    - perl-html-parser
    - perl-uri
    - perl-http-cookies
    - perl-http-date
    - perl-libwww-perl

test:
  imports:
    - LWP::Simple

about:
  home: https://metacpan.org/pod/LWP::Simple
  license: Perl
  summary: simple procedural interface to LWP
