{% set version = "2.0.0" %}

package:
  name: mob_suite
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://github.com/phac-nml/mob-suite/archive/{{ version }}.tar.gz
  sha256: 221dc24eb6d98b119c25cabff5110709cd345790d9836cf5865bec9262fddc3f 


requirements:
  host:
    - python >=3.4,<3.7
    - pip
    - setuptools
  run:
    - python >=3.4
    - pycurl >=7.43
    - scipy >=1.1
    - numpy >=1.11
    - biopython >=1.70
    - pandas >=0.22.0
    - pytables >=3.3
    - blast
    - mash
    - circlator

test:
  commands:
    - "mob_typer -h"
    - "mob_recon -h"

about:
  home: https://github.com/phac-nml/mob-suite
  license: Apache License, Version 2.0
  summary: 'This package MOB-suite: software tools for clustering, reconstruction and typing of plasmids from draft assemblies. The MOB-suite is designed to be a modular set of tools for the typing and reconstruction of plasmid sequences from WGS assemblies.'
